### ISSUE TITLE
The file could not be loaded due to an error.

### ISSUE THREAD

**Issue by MrDrone-ru** [CoderLine/alphaTab#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I found a file, that causes ScoreLoader error during loading. 
I couldn't figure out what exactly in the file is causing the error, maybe the problem is not in it.
`[ScoreLoader] Score import failed due to unexpected error:
RangeError: Invalid typed array length: -2 alphaTab.js:1289
at new Uint8Array (<anonymous>)
at GpBinaryHelpers.gpReadString (alphaTab.js:8834:21)
at GpBinaryHelpers.gpReadStringIntByte (alphaTab.js:8831:36)
at Gp3To5Importer.readMasterBar (alphaTab.js:7890:48)
at Gp3To5Importer.readMasterBars (alphaTab.js:7825:22)
at Gp3To5Importer.readScore (alphaTab.js:7728:18)
at ScoreLoader.loadScoreFromBytes (alphaTab.js:25710:38)
at xhr.onreadystatechange (alphaTab.js:25662:53)`

### Expected Behavior

loading and possibility to play
[Styles of beyond - Nine Thou (NFS MW).zip](https://github.com/CoderLine/alphaTab/files/9905761/Styles.of.beyond.-.Nine.Thou.NFS.MW.zip)

### Steps To Reproduce

try to play the file

### Found in Version

1.3-alpha

### Platform

Web

### Environment

```markdown
win 10 home 21h2
opera 91.0.4516.77
alphatab@1.3.0-alpha.425
```

**Comment by Danielku15** [comment]
Looks like there is a 1 byte shift at the last `Outro` section. GP7/GP8 reads it fine. I will have to check where this shift comes in.

**Comment by MrDrone-ru** [comment]
I'm sorry, but is this fixed?
I use cdn.jsdelivr.net/npm/@coderline/alphatab@1.3.0-alpha.439/dist/alphaTab.js
and reload page with recache files.
file still can't be loaded. with same error(
