### ISSUE TITLE
[BUG] In All versions - Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by DevJett** [CoderLine/alphaTab#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm facing a bug in all versions of Alphatab

```
An unexpected error occurred in worker TypeError: Cannot read properties of undefined (reading 'name')
    at Ga.createNewGlyph (alphatab.worker.a469f53e.js:1:450304)
    at xa.createOrResizeGlyph (alphatab.worker.a469f53e.js:1:442386)
    at xa.createGlyph (alphatab.worker.a469f53e.js:1:442151)
    at La.createVoiceGlyphs (alphatab.worker.a469f53e.js:1:447485)
    at La.createBeatGlyphs (alphatab.worker.a469f53e.js:1:447220)
    at La.doLayout (alphatab.worker.a469f53e.js:1:436719)
    at Pr.addBar (alphatab.worker.a469f53e.js:1:475262)
    at Mr.addBars (alphatab.worker.a469f53e.js:1:484039)
    at Hr.createStaveGroup (alphatab.worker.a469f53e.js:1:505046)
    at Hr.layoutAndRenderScore (alphatab.worker.a469f53e.js:1:503920)
   ```
   

### Expected Behavior

Expected result like Guitar Pro Software

<img width="1339" alt="Screenshot 2023-07-04 at 23 08 33" src="https://github.com/CoderLine/alphaTab/assets/33762501/e469d523-086b-4ac6-8393-ff66695a8040">

### Steps To Reproduce

1. Go to https://www.alphatab.net/ 
2. Download GP File: [If_I_Had_the_World_to_Give_Remaster.gp.zip].(https://github.com/CoderLine/alphaTab/files/11952301/If_I_Had_the_World_to_Give_Remaster.gp.zip)
3. Choose Last Track
4. It will through an error `TypeError: Cannot read properties of undefined (reading 'name')`

### Found in Version

1.2

### Platform

Web

### Environment

```markdown
- **OS**: MacOS
- **Browser**: Chrome
- **.net Version**: All versions
```

**Comment by DevJett** [comment]
Error is coming from 
File name `ChordsEffectInfo.ts`

`createNewGlyph` function

```
public createNewGlyph(renderer: BarRendererBase, beat: Beat): EffectGlyph {
    return new TextGlyph(0, 0, beat.chord!.name, renderer.resources.effectFont, TextAlign.Center);
}
```
Maybe it should be 
```
return new TextGlyph(0, 0, beat.chord?.name || '', renderer.resources.effectFont, TextAlign.Center);
```

**Comment by Danielku15** [comment]
The file you provided seems corrupt. If I open it in Guitar Pro 7.6 Build 2089 (Windows) and Guitar Pro 8.1.0 Build 48 and both crash with the provided file. Even if I fix the chord part the track seems empty and not properly working:

![image](https://github.com/CoderLine/alphaTab/assets/674916/5880aee4-baf3-4152-b2e8-31e8a97dca5f)

The file was very likely not produced by Guitar Pro. A good indication for that is that the IDs in the file are not 0-based indexes. It is not mandatory to work with alphaTab but shows that the problem might be rather in the file and the software that produced the file.

![image](https://github.com/CoderLine/alphaTab/assets/674916/c2ff1fbc-37a8-4e3e-a17f-72603707ee4d)

Did you upload maybe a wrong file? If not, the problem should be rather reported to PaidTabs.com

**Comment by Danielku15** [comment]
@DevJett Any feedback on this topic?

**Comment by Danielku15** [comment]
Closing due to inactivity and likely corrupt files created by a 3rd party service.
