### ISSUE TITLE
AlphaTex Note Effects

### ISSUE THREAD

**Issue by gburlet** [CoderLine/alphaTab#79]
Hi Daniel,

I'm trying to display some tablature with note effects. When inputting these effects using AlphaTex, several of them display improperly or cause AlphaTab to crash with the following error:
```
Error
    at Object.AlphaTab.Importer.AlphaTexImporter.ReadScore (https://rawgit.com/CoderLine/alphaTab/master/Build/JavaScript/AlphaTab.js:2621:88)
    at Object.AlphaTab.Platform.JavaScript.JsApi.Tex (https://rawgit.com/CoderLine/alphaTab/master/Build/JavaScript/AlphaTab.js:982:37)
    at Object.AlphaTab.Platform.JavaScript.JsApiBase (https://rawgit.com/CoderLine/alphaTab/master/Build/JavaScript/AlphaTab.js:582:14)
    at Object.AlphaTab.Platform.JavaScript.JsApi (https://rawgit.com/CoderLine/alphaTab/master/Build/JavaScript/AlphaTab.js:941:44)
    at api.init (https://rawgit.com/CoderLine/alphaTab/master/Build/JavaScript/jquery.alphaTab.js:27:31)
    at apiExec (https://rawgit.com/CoderLine/alphaTab/master/Build/JavaScript/jquery.alphaTab.js:78:32)
    at $.fn.alphaTab (https://rawgit.com/CoderLine/alphaTab/master/Build/JavaScript/jquery.alphaTab.js:88:20)
    at http://fiddle.jshell.net/_display/:54:4
    at jQuery.event.dispatch (http://code.jquery.com/jquery-git.js:5045:27)
    at jQuery.event.add.elemData.handle (http://code.jquery.com/jquery-git.js:4857:28)
```

Here's a fiddle that has the AlphaTex used in one of your demos for the old version (first iteration) of AlphaTab that goes over the supported note effects: http://jsfiddle.net/hdsjuxp9/1. It doesn't compile, but you can manipulate the example and go through each note effect and see what I'm talking about.

Here's a rundown of what's broken:
1. Dead notes ```{x}``` cause a crash.
2. Trills cause a crash.
3. Tremolo causes a crash.
4. Slides and hammer-ons seem to work okay.
5. Harmonics seem to display okay, but are missing text above the staff indicating which type of harmonic they are (though that may be by design in the new version, so not necessarily a bug).
6. Grace notes cause a crash.
7. Vibrato is okay.
8. Ghost notes are okay.
9. Palm mute and Let ring also look okay.
10. Some bends have odd fractions being displayed: 
For example, this AlphaTex:
```
15.6{b(0 4)} 18.6{b(0 6)} 17.6{b(0 8)} 16.6{b(0 3 0)} | 15.6{b(0 8 1)} 14.6{b(0 4)} 13.6{b(0 4 6)} 14.6{b(0 4 0)}
```
is rendered like this:
![bends](https://cloud.githubusercontent.com/assets/1033190/12345688/92410ee0-bb09-11e5-9156-f2b5b3ed09f2.png)

while it looks like this in Guitar Pro:
![bends_gp](https://cloud.githubusercontent.com/assets/1033190/12345699/a23dedd6-bb09-11e5-8dd4-c56c1685ecb2.png)

It's possible I'm inputting wrong values for the bends in AlphaTex, and if that's the case can you send me an email with some details about what I'm doing wrong?

I would be really appreciative of a patch for these note effects!

Cheers,
Greg

**Comment by Danielku15** [comment]
Hi Greg. 
Thanks for this detailed reports. I'll have a look into it soon.

**Comment by Danielku15** [comment]
1. Dead notes are used by setting the fret to `x` not using `{x}` in the effect list. But for convenience I added also the support for `{x}`
2. Fixed and added tests
3. Fixed and added tests
5. Looks like I missed this feature somehow in the new version, I added a basic rendering of the harmonics as texts. 
6. Fixed and added tests
10. The wrong rendering was a mix of bugs and wrong values. I reworked the rendering of the bends a bit to make it look like Guitar Pro 6. 
    * Factions are now rendered using a unicode character (improved)
    * Added rendering of pre-bends (new)
    * Fixed issue where wrong factions are calculated (fixed)
    * Guitar Pro 6 like offsets for lines. (improved)

The Guitar Pro example would be this code in alphaTex: 

	:4 15.6{b(0 4)} 18.6{b(0 6)} 17.6{b(0 8)} 16.6{b(0 3 0)} | 15.6{b(0 8 4)} 14.6{b(4 4)} 13.6{b(4 6)} 14.6{b(4 0)}

**Comment by gburlet** [comment]
Awesome, thanks for the patches Daniel! :+1:
